DROP DATABASE IF EXISTS MD;
CREATE DATABASE MD;
USE MD;

CREATE TABLE Director ( 
  DirectorID INTEGER NOT NULL, 
  Name VARCHAR(30), 
  CONSTRAINT Director_PK PRIMARY KEY (DirectorID)
);

CREATE TABLE Movie ( 
  MovieID INTEGER NOT NULL, 
  Title VARCHAR(30),
  ProductionYear INTEGER,
  DirectorID INTEGER NOT NULL,
  CONSTRAINT Movie_PK PRIMARY KEY (MovieID),
  CONSTRAINT Movie_FK1 FOREIGN KEY (DirectorID) REFERENCES Director(DirectorID)
);

CREATE TABLE Actor ( 
  ActorID	INTEGER NOT NULL,
  Name VARCHAR(30),
  BirthYear INTEGER,
  CONSTRAINT Actor_PK PRIMARY KEY (ActorID) 
);

CREATE TABLE Genre ( 
  GenreID	INTEGER NOT NULL,
  Name VARCHAR(30),
  Description VARCHAR(300),
  CONSTRAINT Genre_PK PRIMARY KEY (GenreID) 
);

CREATE TABLE ActorInMovie ( 
  MovieID INTEGER NOT NULL, 
  ActorID INTEGER NOT NULL,
  Role VARCHAR(30),
  CONSTRAINT ActorInMovie_PK PRIMARY KEY (MovieID, ActorID), 
  CONSTRAINT ActorInMovie_FK1 FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE,
  CONSTRAINT ActorInMovie_FK2 FOREIGN KEY (ActorID) REFERENCES Actor(ActorID) ON DELETE CASCADE
);

CREATE TABLE GenreInMovie ( 
  GenreID INTEGER NOT NULL,
  MovieID INTEGER NOT NULL,
  CONSTRAINT GenreInMovie_PK PRIMARY KEY (MovieID, GenreID),
  CONSTRAINT GenreInMovie_FK1 FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE, 
  CONSTRAINT GenreInMovie_FK2 FOREIGN KEY (GenreID) REFERENCES Genre(GenreID) ON DELETE CASCADE 
);
